--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ExodusDevs/Cooldown
build-by-default: true
branches:
- stable
projects:
  Cooldown:
    path: ""
    model: virion
    type: library
...